/*
	Pululate city table
*/
INSERT INTO Cities (enabled, name, id_state) VALUES 
(true, 'Acrelândia', 1),
(true, 'Água Branca', 2),
(true, 'Alvarães', 3),
(true, 'Amapá', 4),
(true, 'Abaíra', 5),
(true, 'Abaiara', 6),
(true, 'Brasília', 7),
(true, 'Afonso Cláudio', 8),
(true, 'Abadiânia', 9),
(true, 'Açailândia', 10),
(true, 'Abadia dos Dourados', 11),
(true, 'Água Clara', 12),
(true, 'Acorizal', 13),
(true, 'Abaetetuba', 14),
(true, 'Água Branca', 15),
(true, 'Abreu e Lima', 16),
(true, 'Acauã', 17),
(true, 'Abatiá', 18),
(true, 'Angra dos Reis', 19),
(true, 'Acari', 20),
(true, 'Alta Floresta d''Oeste', 21),
(true, 'Alto Alegre', 22),
(true, 'Aceguá', 23),
(true, 'Abdon Batista', 24),
(true, 'Aquidabã', 25),
(true, 'Adamantina', 26),
(true, 'Abreulândia', 27);